# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x06mainpb\"\xb9\x01\n\x08UserData\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05\x63oins\x18\x05 \x01(\x03\x12\x0e\n\x06rating\x18\x06 \x01(\x03\x12\x0c\n\x04role\x18\x07 \x01(\x03\x12\x14\n\x0ctelegramLink\x18\x08 \x01(\t\x12\x12\n\ngithubLink\x18\t \x01(\t\x12\x12\n\navatarPath\x18\n \x01(\t\"+\n\x08\x41uthData\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x0b\x41\x63\x63\x65ssToken\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x11\n\ttokenType\x18\x02 \x01(\t\"\xfd\x01\n\rMarketProduct\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x11\n\x04info\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x03 \x01(\x03H\x01\x88\x01\x01\x12\x12\n\x05title\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04\x63ost\x18\x05 \x01(\x03H\x03\x88\x01\x01\x12\x19\n\x0cremainAmount\x18\x06 \x01(\x03H\x04\x88\x01\x01\x12\x12\n\x05\x61\x62out\x18\x07 \x01(\tH\x05\x88\x01\x01\x12\x16\n\timagePath\x18\x08 \x01(\tH\x06\x88\x01\x01\x42\x07\n\x05_infoB\x05\n\x03_idB\x08\n\x06_titleB\x07\n\x05_costB\x0f\n\r_remainAmountB\x08\n\x06_aboutB\x0c\n\n_imagePath\"8\n\x0eMarketProducts\x12&\n\x07product\x18\x01 \x03(\x0b\x32\x15.mainpb.MarketProductb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERDATA._serialized_start=23
  _USERDATA._serialized_end=208
  _AUTHDATA._serialized_start=210
  _AUTHDATA._serialized_end=253
  _ACCESSTOKEN._serialized_start=255
  _ACCESSTOKEN._serialized_end=308
  _MARKETPRODUCT._serialized_start=311
  _MARKETPRODUCT._serialized_end=564
  _MARKETPRODUCTS._serialized_start=566
  _MARKETPRODUCTS._serialized_end=622
# @@protoc_insertion_point(module_scope)
