"""Fix token int to str

Revision ID: 07ebaaabc403
Revises: b0e21f1b69aa
Create Date: 2022-12-13 22:20:33.764763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ebaaabc403'
down_revision = 'b0e21f1b69aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
