"""Market table

Revision ID: 132ccfbeec04
Revises: ed981c60e28c
Create Date: 2022-10-07 16:42:38.687143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132ccfbeec04'
down_revision = 'ed981c60e28c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
