"""Market table

Revision ID: 25433e2d0885
Revises: 132ccfbeec04
Create Date: 2022-10-07 16:44:11.518573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25433e2d0885'
down_revision = '132ccfbeec04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
