"""Add learning class to user model

Revision ID: 29ae334beb69
Revises: 9c73c470abd8
Create Date: 2022-12-11 22:12:54.395393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ae334beb69'
down_revision = '9c73c470abd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('learningClass', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'learningClass')
    # ### end Alembic commands ###
