"""Add Middle Name and Kaggle

Revision ID: 33069bc475cf
Revises: 6d1e344e650e
Create Date: 2022-11-21 20:01:46.289207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33069bc475cf'
down_revision = '6d1e344e650e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middleName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userKaggle', sa.String(), nullable=True))
    op.drop_column('users', 'coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'userKaggle')
    op.drop_column('users', 'middleName')
    # ### end Alembic commands ###
