"""Array for achievements

Revision ID: 3b2ca917e92a
Revises: bb68a33138d2
Create Date: 2022-12-21 21:19:57.815347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2ca917e92a'
down_revision = 'bb68a33138d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('systemAchievements', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'systemAchievements')
    # ### end Alembic commands ###
