"""Notifications to string

Revision ID: 42dcba190375
Revises: 50115399fc16
Create Date: 2023-01-04 16:58:15.269728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dcba190375'
down_revision = '50115399fc16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
