"""Remove

Revision ID: 4a71335299bc
Revises: c5afab822b56
Create Date: 2023-01-15 19:30:52.709044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a71335299bc'
down_revision = 'c5afab822b56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'func_name')
    op.drop_column('tasks', 'input_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('input_types', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('func_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
