"""Notifications viewed false default

Revision ID: 4e15fd3b8f25
Revises: bb2a0efae9e5
Create Date: 2023-01-04 18:15:28.132556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e15fd3b8f25'
down_revision = 'bb2a0efae9e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
