"""Add Achievements table

Revision ID: 5bd4f36de97c
Revises: 33069bc475cf
Create Date: 2022-12-10 19:58:36.939648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd4f36de97c'
down_revision = '33069bc475cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
