"""Token id

Revision ID: 61466459d594
Revises: f2a1cee0c854
Create Date: 2022-12-13 22:26:03.253717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61466459d594'
down_revision = 'f2a1cee0c854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('oauth_tokens', sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
