"""Add db.tasks table

Revision ID: 6369286c2f1e
Revises: 866fa332fc54
Create Date: 2023-01-12 18:22:40.226371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6369286c2f1e'
down_revision = '866fa332fc54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('tests', sa.PickleType(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'tests')
    op.drop_column('tasks', 'author_id')
    # ### end Alembic commands ###
