"""Market table

Revision ID: 65a37a03194d
Revises: 6f30dcd74387
Create Date: 2022-10-07 16:40:32.006859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a37a03194d'
down_revision = '6f30dcd74387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
