"""“Patch”

Revision ID: 6d1e344e650e
Revises: 058fe390b20d
Create Date: 2022-11-21 19:57:32.783148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1e344e650e'
down_revision = '058fe390b20d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userStepik', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userStepik')
    # ### end Alembic commands ###
