"""Add Achievements table fix

Revision ID: 9c73c470abd8
Revises: 5bd4f36de97c
Create Date: 2022-12-10 20:01:25.351106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c73c470abd8'
down_revision = '5bd4f36de97c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'achievements', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='unique')
    # ### end Alembic commands ###
