"""Add db.contests table/model

Revision ID: a99ba6ea9e74
Revises: 6369286c2f1e
Create Date: 2023-01-12 18:29:36.070924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99ba6ea9e74'
down_revision = '6369286c2f1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
