"""Sync

Revision ID: b0e21f1b69aa
Revises: e87bac6f19d0
Create Date: 2022-12-13 19:21:28.260377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e21f1b69aa'
down_revision = 'e87bac6f19d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oauth_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_tokens', type_='unique')
    # ### end Alembic commands ###
