"""Contest tests

Revision ID: b5cd56890076
Revises: 4a71335299bc
Create Date: 2023-01-15 20:40:53.535204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cd56890076'
down_revision = '4a71335299bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('contest_tests', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'contest_tests')
    # ### end Alembic commands ###
