"""Notifications viewed

Revision ID: bb2a0efae9e5
Revises: e556832cfdfc
Create Date: 2023-01-04 18:14:31.169887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2a0efae9e5'
down_revision = 'e556832cfdfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('viewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'viewed')
    # ### end Alembic commands ###
