"""Tasks input types and func name

Revision ID: bd0af384c383
Revises: b5cd56890076
Create Date: 2023-01-15 21:54:12.492371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd0af384c383'
down_revision = 'b5cd56890076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('input_types', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('tasks', sa.Column('func_name', sa.String(), nullable=True))
    op.drop_column('tasks', 'contest_tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('contest_tests', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'func_name')
    op.drop_column('tasks', 'input_types')
    # ### end Alembic commands ###
