"""Default rating for user

Revision ID: c06d82302947
Revises: e1b9561fc796
Create Date: 2023-01-11 20:13:38.249917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06d82302947'
down_revision = 'e1b9561fc796'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
