"""Add verified column to app

Revision ID: ce14a2f25d34
Revises: f3f874ea59af
Create Date: 2022-12-11 23:56:02.491840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce14a2f25d34'
down_revision = 'f3f874ea59af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thirdparty_apps', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thirdparty_apps', 'verified')
    # ### end Alembic commands ###
