"""Market table

Revision ID: dcae3fe742c3
Revises: 6c56f2483c62
Create Date: 2022-10-07 16:50:44.124021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcae3fe742c3'
down_revision = '6c56f2483c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
