"""Postgres json

Revision ID: df99a450cb06
Revises: 87d50b428eaf
Create Date: 2023-01-05 19:36:55.770759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df99a450cb06'
down_revision = '87d50b428eaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
