"""Add redirect url to app

Revision ID: e87bac6f19d0
Revises: ce14a2f25d34
Create Date: 2022-12-12 21:42:32.523172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87bac6f19d0'
down_revision = 'ce14a2f25d34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thirdparty_apps', sa.Column('redirect_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thirdparty_apps', 'redirect_url')
    # ### end Alembic commands ###
