"""Naming

Revision ID: eb2865205a32
Revises: dcae3fe742c3
Create Date: 2022-10-07 18:16:06.625243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2865205a32'
down_revision = 'dcae3fe742c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_products', sa.Column('remainAmount', sa.Integer(), nullable=True))
    op.add_column('market_products', sa.Column('imagePath', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'market_products', ['id'])
    op.drop_column('market_products', 'image_path')
    op.drop_column('market_products', 'remain_amount')
    op.add_column('users', sa.Column('hashedPassword', sa.String(), nullable=True))
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userRole', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('userTelegram', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userGithub', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userAboutText', sa.String(), nullable=True))
    op.add_column('users', sa.Column('userAvatarPath', sa.String(), nullable=True))
    op.drop_column('users', 'user_about_text')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'user_telegram')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'user_role')
    op.drop_column('users', 'user_avatar_path')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'user_github')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_github', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_avatar_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_telegram', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_about_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'userAvatarPath')
    op.drop_column('users', 'userAboutText')
    op.drop_column('users', 'userGithub')
    op.drop_column('users', 'userTelegram')
    op.drop_column('users', 'userRole')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'hashedPassword')
    op.add_column('market_products', sa.Column('remain_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('market_products', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'market_products', type_='unique')
    op.drop_column('market_products', 'imagePath')
    op.drop_column('market_products', 'remainAmount')
    # ### end Alembic commands ###
