"""Market table

Revision ID: ed981c60e28c
Revises: 65a37a03194d
Create Date: 2022-10-07 16:41:43.624711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed981c60e28c'
down_revision = '65a37a03194d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
