"""Add thirdparty apps table

Revision ID: f3f874ea59af
Revises: 29ae334beb69
Create Date: 2022-12-11 23:44:29.325975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f874ea59af'
down_revision = '29ae334beb69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'thirdparty_apps', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thirdparty_apps', type_='unique')
    # ### end Alembic commands ###
