"""

Revision ID: 0e709fffcc00
Revises: f1013cfc16f2
Create Date: 2023-05-01 20:38:48.622532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e709fffcc00'
down_revision = 'f1013cfc16f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
