"""

Revision ID: 2aef1ac39c5b
Revises: feb9438501f7
Create Date: 2023-04-01 19:27:10.184145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aef1ac39c5b'
down_revision = 'feb9438501f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
