"""Add db.contests table/model

Revision ID: 435dd19c61f3
Revises: a99ba6ea9e74
Create Date: 2023-01-12 18:29:58.698121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435dd19c61f3'
down_revision = 'a99ba6ea9e74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contests', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contests', type_='unique')
    # ### end Alembic commands ###
