"""Notifications

Revision ID: 50115399fc16
Revises: 3b2ca917e92a
Create Date: 2023-01-04 16:10:28.357588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50115399fc16'
down_revision = '3b2ca917e92a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    # ### end Alembic commands ###
