"""

Revision ID: 65ecb7ac85c8
Revises: 51ee25eff0b0
Create Date: 2023-04-01 22:51:20.798196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ecb7ac85c8'
down_revision = '51ee25eff0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
