"""

Revision ID: 82df5906c781
Revises: 1e6cc1f4505a
Create Date: 2023-05-01 20:23:15.688477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82df5906c781'
down_revision = '1e6cc1f4505a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_to_user_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['to_user'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('types', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('tasks', 'input_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('input_types', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'types')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_to_user_fkey', 'notifications', 'users', ['to_user'], ['id'])
    # ### end Alembic commands ###
