"""Add website field

Revision ID: 866fa332fc54
Revises: c06d82302947
Create Date: 2023-01-11 22:04:43.941819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866fa332fc54'
down_revision = 'c06d82302947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userWebsite', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userWebsite')
    # ### end Alembic commands ###
