"""Attachments for achievements

Revision ID: 87d50b428eaf
Revises: 4e15fd3b8f25
Create Date: 2023-01-05 18:21:45.569583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d50b428eaf'
down_revision = '4e15fd3b8f25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('attachment_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'attachment_file_name')
    # ### end Alembic commands ###
