"""Add db.tasks imput types

Revision ID: acf65fc8391f
Revises: c41e701707ef
Create Date: 2023-01-15 18:20:54.990772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf65fc8391f'
down_revision = 'c41e701707ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('input_types', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'input_types')
    # ### end Alembic commands ###
