"""Nullable accepted by ach

Revision ID: bb68a33138d2
Revises: 
Create Date: 2022-12-18 14:35:46.879570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb68a33138d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'accepted_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'achievements', ['id'])
    op.create_unique_constraint(None, 'oauth_tokens', ['entry_id'])
    op.create_unique_constraint(None, 'thirdparty_apps', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thirdparty_apps', type_='unique')
    op.drop_constraint(None, 'oauth_tokens', type_='unique')
    op.drop_constraint(None, 'achievements', type_='unique')
    op.alter_column('achievements', 'accepted_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
