"""

Revision ID: bfe20ae55471
Revises: 598b5ed97017
Create Date: 2023-05-01 20:39:24.844007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe20ae55471'
down_revision = '598b5ed97017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('types', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'types')
    # ### end Alembic commands ###
