"""Add db.submits datetime column; send date

Revision ID: c41e701707ef
Revises: fb4ec679885a
Create Date: 2023-01-14 00:07:10.291023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41e701707ef'
down_revision = 'fb4ec679885a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submits', sa.Column('send_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submits', 'send_date')
    # ### end Alembic commands ###
