"""Notifications jsoin

Revision ID: e556832cfdfc
Revises: 42dcba190375
Create Date: 2023-01-04 17:02:06.563196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e556832cfdfc'
down_revision = '42dcba190375'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
