"""Add db.submits model/table

Revision ID: fb4ec679885a
Revises: 435dd19c61f3
Create Date: 2023-01-12 18:36:58.818228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4ec679885a'
down_revision = '435dd19c61f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'submits', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submits', type_='unique')
    # ### end Alembic commands ###
