"""

Revision ID: feb9438501f7
Revises: fc4b2f260f15
Create Date: 2023-04-01 19:27:01.230963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb9438501f7'
down_revision = 'fc4b2f260f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'polls', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'polls', type_='unique')
    # ### end Alembic commands ###
