"""

Revision ID: 0261e69a80a9
Revises: f639e9fa75ca
Create Date: 2023-08-18 13:08:06.664204

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0261e69a80a9'
down_revision = 'f639e9fa75ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submits', 'userId',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('fk_submits_userId_users', 'submits', type_='foreignkey')
    op.create_foreign_key(None, 'submits', 'users', ['userId'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submits', type_='foreignkey')
    op.create_foreign_key('fk_submits_userId_users', 'submits', 'users', ['userId'], ['uuid'])
    op.alter_column('submits', 'userId',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###