"""

Revision ID: 0d714be3d7d5
Revises: 572aec0bbafb
Create Date: 2023-08-18 13:26:16.628382

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0d714be3d7d5'
down_revision = '572aec0bbafb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###