"""

Revision ID: 0e7ec05efe82
Revises: ad01541f02e6
Create Date: 2023-08-17 11:50:36.586857

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e7ec05efe82'
down_revision = 'ad01541f02e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'acceptedBy',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'acceptedBy',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###