"""

Revision ID: 15de4be52935
Revises: d1e4d2edf5de
Create Date: 2023-08-01 20:41:30.802701

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '15de4be52935'
down_revision = 'd1e4d2edf5de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###