"""

Revision ID: 16b4c27df37c
Revises: a203ddea7a9c
Create Date: 2023-08-02 19:49:35.268562

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '16b4c27df37c'
down_revision = 'a203ddea7a9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###