"""

Revision ID: 19fa25e7bc84
Revises: bcda665d143f
Create Date: 2023-08-18 21:12:16.639350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '19fa25e7bc84'
down_revision = 'bcda665d143f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###