"""UUID

Revision ID: 48da2bb11cec
Revises: 19fa25e7bc84
Create Date: 2023-08-20 14:17:40.328998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48da2bb11cec'
down_revision = '19fa25e7bc84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contests', 'tasks',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(postgresql.UUID(as_uuid=1)),
               existing_nullable=True)
    op.alter_column('contests', 'forGroups',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(postgresql.UUID(as_uuid=1)),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contests', 'forGroups',
               existing_type=sa.ARRAY(postgresql.UUID(as_uuid=1)),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('contests', 'tasks',
               existing_type=sa.ARRAY(postgresql.UUID(as_uuid=1)),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###