"""

Revision ID: 572aec0bbafb
Revises: 0261e69a80a9
Create Date: 2023-08-18 13:22:03.387010

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '572aec0bbafb'
down_revision = '0261e69a80a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_achievements_acceptedBy_users', 'achievements', type_='foreignkey')
    op.create_foreign_key(None, 'achievements', 'users', ['acceptedBy'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('fk_submits_userId_users', 'submits', type_='foreignkey')
    op.drop_column('submits', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submits', sa.Column('userId', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_submits_userId_users', 'submits', 'users', ['userId'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_foreign_key('fk_achievements_acceptedBy_users', 'achievements', 'users', ['acceptedBy'], ['uuid'])
    # ### end Alembic commands ###