"""Deadline

Revision ID: 5b93bb4378a5
Revises: 48da2bb11cec
Create Date: 2023-08-20 14:52:25.921475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5b93bb4378a5'
down_revision = '48da2bb11cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('deadline', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'deadline')
    # ### end Alembic commands ###