"""user

Revision ID: 6254d1bb3ead
Revises: 
Create Date: 2023-06-04 19:16:31.509138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = '6254d1bb3ead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('role', postgresql.ENUM('student', 'teacher', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('learningClass', sa.Integer(), nullable=False),
    sa.Column('nickName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('patronymicName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('avatarPath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('github', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('stepik', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('kaggle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('techStack', sqlmodel.sql.sqltypes.AutoString(length=800), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('kaggle'),
    sa.UniqueConstraint('nickName'),
    sa.UniqueConstraint('stepik'),
    sa.UniqueConstraint('telegram'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
