"""

Revision ID: 71e75558909e
Revises: c64e6871cd47
Create Date: 2023-09-03 14:40:49.859034

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '71e75558909e'
down_revision = 'c64e6871cd47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('mark5', sa.Integer(), nullable=True))
    op.add_column('contests', sa.Column('mark4', sa.Integer(), nullable=True))
    op.add_column('contests', sa.Column('mark3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'mark3')
    op.drop_column('contests', 'mark4')
    op.drop_column('contests', 'mark5')
    # ### end Alembic commands ###