"""

Revision ID: 8310e10a6ec9
Revises: 16b4c27df37c
Create Date: 2023-08-02 21:05:06.637064

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8310e10a6ec9'
down_revision = '16b4c27df37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('role', postgresql.ENUM('olimpiad', 'event', name='eventType'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('toUser', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('acceptedBy', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('attachmentName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('acceptedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acceptedBy'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['toUser'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_achievements_uuid'), 'achievements', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_achievements_uuid'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###