"""

Revision ID: 947d7a05430f
Revises: fca1b5cb3e6c
Create Date: 2023-08-17 22:21:31.950813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '947d7a05430f'
down_revision = 'fca1b5cb3e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###