"""

Revision ID: 95397c551c8d
Revises: 0d714be3d7d5
Create Date: 2023-08-18 13:28:05.773292

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '95397c551c8d'
down_revision = '0d714be3d7d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###