"""Users

Revision ID: 95496b3c2dea
Revises: 954f330089fb
Create Date: 2023-06-04 22:34:07.688475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '95496b3c2dea'
down_revision = '954f330089fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aboutText', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aboutText')
    # ### end Alembic commands ###