"""

Revision ID: ad01541f02e6
Revises: 8310e10a6ec9
Create Date: 2023-08-17 11:16:22.574458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ad01541f02e6'
down_revision = '8310e10a6ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###