"""

Revision ID: b94fb058a8bb
Revises: 947d7a05430f
Create Date: 2023-08-18 12:51:25.752320

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b94fb058a8bb'
down_revision = '947d7a05430f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###