"""User

Revision ID: ba83a73c65bd
Revises: 95496b3c2dea
Create Date: 2023-06-05 00:05:56.827402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ba83a73c65bd'
down_revision = '95496b3c2dea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###