"""

Revision ID: bcda665d143f
Revises: bf5d0cfe81e7
Create Date: 2023-08-18 20:24:31.582696

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcda665d143f'
down_revision = 'bf5d0cfe81e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'acceptedBy',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'acceptedBy',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###