"""

Revision ID: bf5d0cfe81e7
Revises: d08bfa70180b
Create Date: 2023-08-18 13:57:03.692178

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf5d0cfe81e7'
down_revision = 'd08bfa70180b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submits', sa.Column('userId', postgresql.UUID(as_uuid=1), nullable=True))
    op.create_foreign_key(None, 'submits', 'users', ['userId'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submits', type_='foreignkey')
    op.drop_column('submits', 'userId')
    # ### end Alembic commands ###