"""

Revision ID: c64e6871cd47
Revises: a6927410a7cb
Create Date: 2023-09-02 19:49:37.628848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c64e6871cd47'
down_revision = 'a6927410a7cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_notifications', sa.Column('authorId', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_notifications', 'authorId')
    # ### end Alembic commands ###