"""

Revision ID: f639e9fa75ca
Revises: fe5b2a029e41
Create Date: 2023-08-18 13:03:05.298403

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f639e9fa75ca'
down_revision = 'fe5b2a029e41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'toUser',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('fk_achievements_toUser_users', 'achievements', type_='foreignkey')
    op.create_foreign_key(None, 'achievements', 'users', ['toUser'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_foreign_key('fk_achievements_toUser_users', 'achievements', 'users', ['toUser'], ['uuid'])
    op.alter_column('achievements', 'toUser',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###