"""

Revision ID: fca1b5cb3e6c
Revises: 1d9c069083a8
Create Date: 2023-08-17 22:19:55.929664

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fca1b5cb3e6c'
down_revision = '1d9c069083a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###