"""

Revision ID: fe5b2a029e41
Revises: b94fb058a8bb
Create Date: 2023-08-18 12:59:30.319560

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe5b2a029e41'
down_revision = 'b94fb058a8bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'toUser',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('fk_notifications_toUser_users', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['toUser'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('fk_notifications_toUser_users', 'notifications', 'users', ['toUser'], ['uuid'])
    op.alter_column('notifications', 'toUser',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###